### ISSUE TITLE
How to add linux kernel mail mirror to your docker environment?

### ISSUE THREAD

**Issue by Dongfang-Qu** [nmenon/public-inbox-docker#1]
I want to use your docker imge to build a local linux kernel mail search service, like https://lore.kernel.org/lkml/, but I don’t understand how to set it up.
thanks!

**Comment by Dongfang-Qu** [comment]
No permission to execute
swuser@b13385886a25:/$ public-inbox-init -V2 -L full --ng inbox.linux-patch-review --skip-artnum 1 --skip-epoch 1 "linux-patch-review" /git-repos/linux-patch-review.git http://example.com/lore/linux-patch-review/ linux-patch-review@example.com
failed to open /workdir/.public-inbox/config.flock: Permission denied

**Comment by nmenon** [comment]
Does'nt -v volume mount help?

**Comment by nmenon** [comment]
I think you need to first look at the mirror instructions..
Example: https://lore.kernel.org/linux-omap/_/text/mirror/

```
cd /tmp
git clone --mirror http://lore.kernel.org/linux-omap/0 linux-omap/git/0.git
docker pull ghcr.io/nmenon/public-inbox
docker run --rm -it -v `pwd`/linux-omap:/linux-omap  ghcr.io/nmenon/public-inbox public-inbox-init -V2 --ng org.kernel.vger.linux-omap  linux-omap /linux-omap http://lore.kernel.org/linux-omap  linux-omap@vger.kernel.org
docker run --rm -it -v `pwd`/linux-omap:/linux-omap  ghcr.io/nmenon/public-inbox public-inbox-index /linux-omap
```

Did I miss something?

**Comment by nmenon** [comment]
Assuming this worked?

**Comment by nmenon** [comment]
Closing.
